version: '3.5'

networks:
  power-stack-net:
    external: true

volumes:
  cloud_data:
    name: cloud_data
  cloud_db_data:
    name: cloud_db_data
  redis_data:


services:
  owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    networks:
      - power-stack-net
    volumes:
      - cloud_data:/mnt/data
    deploy:
      restart_policy: 
        condition: on-failure
        delay: 5s
      labels: 
        - "traefik.enable=true"
        - "traefik.http.services.cloud.loadbalancer.server.port=8080"
        - "traefik.http.routers.cloud.rule=Host(`${OWNCLOUD_DOMAIN}`)"
        - "traefik.http.routers.cloud.entrypoints=https"
        - "traefik.http.routers.cloud.tls.certresolver=letsencrypt"
        - "traefik.http.routers.cloud.tls=true"
        - "traefik.http.routers.cloud.service=cloud"        
    environment:
      - "OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}"
      - "OWNCLOUD_DB_TYPE=mysql"
      - "OWNCLOUD_DB_NAME=${OWNCLOUD_DB_NAME}"
      - "OWNCLOUD_DB_USERNAME=${OWNCLOUD_DB_USERNAME}"
      - "OWNCLOUD_DB_PASSWORD=${OWNCLOUD_DB_PASSWORD}"
      - "OWNCLOUD_DB_HOST=db"
      - "OWNCLOUD_ADMIN_USERNAME=${OWNCLOUD_ADMIN_USERNAME}"
      - "OWNCLOUD_ADMIN_PASSWORD=${OWNCLOUD_ADMIN_PASSWORD}"
      - "OWNCLOUD_MYSQL_UTF8MB4=true"
      - "OWNCLOUD_REDIS_ENABLED=true"
      - "OWNCLOUD_REDIS_HOST=redis"
    logging:
      driver: json-file
      options: 
        max-size: 1m


  db:
    image: mysql:8.0
    deploy:
      restart_policy: 
        condition: on-failure
        delay: 5s    
    command: [
      '--character-set-server=utf8mb4', 
      '--collation-server=utf8mb4_unicode_ci',
      '--default-authentication-plugin=mysql_native_password'
    ]
    networks:
      - power-stack-net
    volumes:
      - cloud_db_data:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${OWNCLOUD_DB_ROOT_PWD}"
      - "MYSQL_USER=${OWNCLOUD_DB_USERNAME}"
      - "MYSQL_PASSWORD=${OWNCLOUD_DB_PASSWORD}"
      - "MYSQL_DATABASE=${OWNCLOUD_DB_NAME}"
      - "MYSQL_MAX_ALLOWED_PACKET=128M"
      - "MYSQL_INNODB_LOG_FILE_SIZE=64M"
    logging:
      driver: json-file
      options: 
        max-size: 1m

  redis:
    image: redis:5.0
    deploy:
      restart_policy: 
        condition: on-failure
        delay: 5s
    networks:
      - power-stack-net
    environment:
      - REDIS_DATABASES=1
    volumes:
      - redis_data:/var/lib/redis
    logging:
      driver: json-file
      options: 
        max-size: 1m
