name: deploy the stack services

# this actions will be triggered via [actionspanel](https://www.actionspanel.app/)
on: repository_dispatch

jobs:

  deploy:
    if: github.event.action == 'deploy_stack'
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: generate private key file
        if: success()
        env: 
          RSA_PRIV_KEY: ${{ secrets.RSA_PRIV_KEY }}
          # RSA_PRIV_KEY_PWD: ${{ secrets.RSA_PRIV_KEY_PWD }}
          VM_DOMAIN: power-stack-master.westeurope.cloudapp.azure.com
        run: |
          mkdir -p ~/.ssh/ && chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          # echo "$RSA_PRIV_KEY" | base64 --decode > ~/.ssh/id_rsa
          echo "$RSA_PRIV_KEY" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

          eval $(ssh-agent -s)
          ssh-keygen -R $VM_DOMAIN || true
          ssh-keyscan -H $VM_DOMAIN >> ~/.ssh/known_hosts
          # echo $RSA_PRIV_KEY_PWD | ssh-add ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa

      # need a docker-compose that supports docker-context
      - name: install compose 
        if: success()
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0-rc3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: create docker context
        if: success()
        env: 
          SSH_HOST: ssh://vbr@power-stack-master.westeurope.cloudapp.azure.com
        run: |
          docker context create power-stack \
              --default-stack-orchestrator "swarm" \
              --docker "host=$SSH_HOST"
          
      - name: deploy proxy
        if: success()
        env: 
          PROXY_DASHBOARD_UI_DOMAIN: ${{ secrets.PROXY_DASHBOARD_UI_DOMAIN }}
          BASIC_AUTH_USR: ${{ secrets.BASIC_AUTH_USR }}
          BASIC_AUTH_PWD: ${{ secrets.BASIC_AUTH_PWD }}
        run: |
          cd ./proxy
          docker context use power-stack
          docker-compose up -d --build 

      - name: deploy monitoring
        if: success()
        env: 
          INFLUXDB_NAME: ${{ secrets.INFLUXDB_NAME }}
          INFLUXDB_USER_NAME: ${{ secrets.INFLUXDB_USER_NAME }}
          INFLUXDB_USER_PWD: ${{ secrets.INFLUXDB_USER_PWD }}
          GRAFANA_USER_NAME: ${{ secrets.GRAFANA_USER_NAME }}
          GRAFANA_USER_PWD: ${{ secrets.GRAFANA_USER_PWD }}
          GRAFANA_WEB_DOMAIN: ${{ secrets.GRAFANA_WEB_DOMAIN }}
          CHRONOGRAF_WEB_DOMAIN: ${{ secrets.CHRONOGRAF_WEB_DOMAIN }}
          DOZZLE_WEB_DOMAIN: ${{ secrets.DOZZLE_WEB_DOMAIN }}
        run: |
          cd ./monitoring
          docker context use power-stack
          docker-compose up -d --build 
