name: deploy the stack services

# this actions will be triggered via [actionspanel](https://www.actionspanel.app/)
on: repository_dispatch

jobs:

  deploy:
    if: github.event.action == 'deploy_stack'
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: generate private key file
        if: success()
        env: 
          SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
          VM_DOMAIN: power-stack-master.westeurope.cloudapp.azure.com
          SSH_HOST: ssh://${{ secrets.SSH_USER }}@power-stack-master.westeurope.cloudapp.azure.com
        run: |
          . ./.github/workflows/prepare.sh

      - name: init swarm
        if: success()
        run: |
          docker context use power-stack
          docker swarm init &>/dev/null || true
          
      - name: deploy utils
        if: success()
        env: 
          PROXY_DASHBOARD_UI_DOMAIN: ${{ secrets.PROXY_DASHBOARD_UI_DOMAIN }}
          BASIC_AUTH_USR: ${{ secrets.BASIC_AUTH_USR }}
          BASIC_AUTH_PWD_HASH: ${{ secrets.BASIC_AUTH_PWD_HASH }}
          REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}
        run: |
          cd ./utils
          docker context use power-stack
          docker stack deploy utils -c docker-compose.yml
          docker service list

      - name: deploy monitoring
        if: success()
        env: 
          INFLUXDB_NAME: ${{ secrets.INFLUXDB_NAME }}
          INFLUXDB_USER_NAME: ${{ secrets.INFLUXDB_USER_NAME }}
          INFLUXDB_USER_PWD: ${{ secrets.INFLUXDB_USER_PWD }}
          GRAFANA_USER_NAME: ${{ secrets.GRAFANA_USER_NAME }}
          GRAFANA_USER_PWD: ${{ secrets.GRAFANA_USER_PWD }}
          GRAFANA_WEB_DOMAIN: ${{ secrets.GRAFANA_WEB_DOMAIN }}
          CHRONOGRAF_WEB_DOMAIN: ${{ secrets.CHRONOGRAF_WEB_DOMAIN }}
          DOZZLE_WEB_DOMAIN: ${{ secrets.DOZZLE_WEB_DOMAIN }}
          REGISTRY_DOMAIN: ${{ secrets.REGISTRY_DOMAIN }}
          BASIC_AUTH_USR: ${{ secrets.BASIC_AUTH_USR }}
          BASIC_AUTH_PWD: ${{ secrets.BASIC_AUTH_PWD }}
        run: |
          cd ./monitoring
          docker context use power-stack
          
          echo "login to repo"
          docker login -u $BASIC_AUTH_USR -p $BASIC_AUTH_PWD $REGISTRY_DOMAIN

          echo "build images"
          docker-compose build
          echo "push images"
          docker-compose push

          echo "start stack"
          docker stack deploy monitoring --with-registry-auth -c docker-compose.yml
          docker service list

    

