name: deploy the stack services

# this actions will be triggered via [actionspanel](https://www.actionspanel.app/)
on: repository_dispatch

jobs:

  deploy:
    if: github.event.action == 'deploy_stack'
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      # - name: Azure Login
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: generate private key file
        if: success()
        env: 
          RSA_PRIV_KEY: ${{ secrets.RSA_PRIV_KEY }}
          STACK_NAME: ${{ secrets.APP_NAME }}    
        run: |
          mkdir -p ~/.ssh/ && chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          chmod 600 ~/.ssh/config
          eval $(ssh-agent -s)
          ssh-keygen -R $STACK_NAME-master.westeurope.cloudapp.azure.com || true
          ssh-add <(echo "$RSA_PRIV_KEY" | base64 --decode)
          ssh-keyscan -H $STACK_NAME-master.westeurope.cloudapp.azure.com >> ~/.ssh/known_hosts

      - name: create docker context
        if: success()
        env: 
          STACK_NAME: ${{ secrets.APP_NAME }}   
          VM_USERNAME: ${{ secrets.VM_USERNAME }}
        run: |
          docker context create power-stack \
              --docker "host=ssh://$VM_USERNAME@$STACK_NAME-master.westeurope.cloudapp.azure.com"
          
      - name: deploy proxy
        if: success()
        env: 
          PROXY_DASHBOARD_UI_DOMAIN: ${{ secrets.PROXY_DASHBOARD_UI_DOMAIN }}
          BASIC_AUTH_USR: ${{ secrets.BASIC_AUTH_USR }}
          BASIC_AUTH_PWD: ${{ secrets.BASIC_AUTH_PWD }}
        run: |
          cd ./proxy
          docker context use power-stack
          docker network ls|grep main-net > /dev/null || docker network create -d overlay --attachable main-net
          docker-compose up -d --build 

      - name: deploy monitoring
        if: success()
        env: 
          INFLUXDB_NAME: ${{ secrets.INFLUXDB_NAME }}
          INFLUXDB_USER_NAME: ${{ secrets.INFLUXDB_USER_NAME }}
          INFLUXDB_USER_PWD: ${{ secrets.INFLUXDB_USER_PWD }}
          GRAFANA_USER_NAME: ${{ secrets.GRAFANA_USER_NAME }}
          GRAFANA_USER_PWD: ${{ secrets.GRAFANA_USER_PWD }}
          GRAFANA_WEB_DOMAIN: ${{ secrets.GRAFANA_WEB_DOMAIN }}
          CHRONOGRAF_WEB_DOMAIN: ${{ secrets.CHRONOGRAF_WEB_DOMAIN }}
          DOZZLE_WEB_DOMAIN: ${{ secrets.DOZZLE_WEB_DOMAIN }}
        run: |
          cd ./monitoring
          docker context use power-stack
          docker-compose up -d --build 
